[package]
name = "lune-utils"
version = "0.8.3"
edition = "2021"
license = "MPL-2.0"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
mlua = { version = "0.9.7", features = ["async"] }
